"""
Country to timezone mapping for aerodrome registry.

This file contains the comprehensive mapping of country ISO codes to their
primary timezones for fallback when OpenFlights doesn't have timezone data.

Coverage: 150+ countries with proper regional timezones

Note: This mapping is derived from publicly available timezone information
and is used as a fallback when OpenFlights data is not available.
"""

# Comprehensive country to timezone mapping
COUNTRY_TIMEZONES = {
    # Europe
    "AL": "Europe/Tirane",
    "AT": "Europe/Vienna",
    "BA": "Europe/Sarajevo",
    "BE": "Europe/Brussels",
    "BG": "Europe/Sofia",
    "BY": "Europe/Minsk",
    "CH": "Europe/Zurich",
    "CZ": "Europe/Prague",
    "DE": "Europe/Berlin",
    "DK": "Europe/Copenhagen",
    "EE": "Europe/Tallinn",
    "ES": "Europe/Madrid",
    "FI": "Europe/Helsinki",
    "FO": "Atlantic/Faroe",
    "FR": "Europe/Paris",
    "GB": "Europe/London",
    "GR": "Europe/Athens",
    "HR": "Europe/Zagreb",
    "HU": "Europe/Budapest",
    "IE": "Europe/Dublin",
    "IS": "Atlantic/Reykjavik",
    "IT": "Europe/Rome",
    "LT": "Europe/Vilnius",
    "LU": "Europe/Luxembourg",
    "LV": "Europe/Riga",
    "MC": "Europe/Monaco",
    "MD": "Europe/Chisinau",
    "ME": "Europe/Podgorica",
    "MK": "Europe/Skopje",
    "NL": "Europe/Amsterdam",
    "NO": "Europe/Oslo",
    "PL": "Europe/Warsaw",
    "PT": "Europe/Lisbon",
    "RO": "Europe/Bucharest",
    "RS": "Europe/Belgrade",
    "SE": "Europe/Stockholm",
    "SI": "Europe/Ljubljana",
    "SK": "Europe/Bratislava",
    "SM": "Europe/San_Marino",
    "TR": "Europe/Istanbul",
    "UA": "Europe/Kiev",
    "XK": "Europe/Belgrade",
    
    # North America
    "CA": "America/Toronto",
    "GL": "America/Godthab",
    "MX": "America/Mexico_City",
    "US": "America/New_York",
    
    # South America
    "AR": "America/Argentina/Buenos_Aires",
    "BO": "America/La_Paz",
    "BR": "America/Sao_Paulo",
    "CL": "America/Santiago",
    "CO": "America/Bogota",
    "EC": "America/Guayaquil",
    "GF": "America/Cayenne",
    "GY": "America/Guyana",
    "PE": "America/Lima",
    "PY": "America/Asuncion",
    "SR": "America/Paramaribo",
    "UY": "America/Montevideo",
    "VE": "America/Caracas",
    
    # Central America & Caribbean
    "AG": "America/Antigua",
    "BB": "America/Barbados",
    "BL": "America/St_Barthelemy",
    "BS": "America/Nassau",
    "BZ": "America/Belize",
    "CR": "America/Costa_Rica",
    "CU": "America/Havana",
    "DO": "America/Santo_Domingo",
    "GD": "America/Grenada",
    "GT": "America/Guatemala",
    "HN": "America/Tegucigalpa",
    "MF": "America/Marigot",
    "NI": "America/Managua",
    "PA": "America/Panama",
    "PR": "America/Puerto_Rico",
    "SV": "America/El_Salvador",
    "TC": "America/Grand_Turk",
    "VG": "America/Tortola",
    
    # Asia
    "AF": "Asia/Kabul",
    "AM": "Asia/Yerevan",
    "AZ": "Asia/Baku",
    "BD": "Asia/Dhaka",
    "BH": "Asia/Bahrain",
    "BT": "Asia/Thimphu",
    "CN": "Asia/Shanghai",
    "CY": "Asia/Nicosia",
    "GE": "Asia/Tbilisi",
    "HK": "Asia/Hong_Kong",
    "ID": "Asia/Jakarta",
    "IL": "Asia/Jerusalem",
    "IN": "Asia/Kolkata",
    "IQ": "Asia/Baghdad",
    "IR": "Asia/Tehran",
    "JP": "Asia/Tokyo",
    "JO": "Asia/Amman",
    "KG": "Asia/Bishkek",
    "KH": "Asia/Phnom_Penh",
    "KP": "Asia/Pyongyang",
    "KR": "Asia/Seoul",
    "KW": "Asia/Kuwait",
    "KZ": "Asia/Almaty",
    "LA": "Asia/Vientiane",
    "LB": "Asia/Beirut",
    "LK": "Asia/Colombo",
    "MM": "Asia/Yangon",
    "MN": "Asia/Ulaanbaatar",
    "MO": "Asia/Macau",
    "MY": "Asia/Kuala_Lumpur",
    "NP": "Asia/Kathmandu",
    "OM": "Asia/Muscat",
    "PH": "Asia/Manila",
    "PK": "Asia/Karachi",
    "QA": "Asia/Qatar",
    "RU": "Europe/Moscow",
    "SA": "Asia/Riyadh",
    "SG": "Asia/Singapore",
    "SY": "Asia/Damascus",
    "TH": "Asia/Bangkok",
    "TJ": "Asia/Dushanbe",
    "TL": "Asia/Dili",
    "TM": "Asia/Ashgabat",
    "TW": "Asia/Taipei",
    "UZ": "Asia/Tashkent",
    "VN": "Asia/Ho_Chi_Minh",
    "YE": "Asia/Aden",
    
    # Africa
    "AE": "Asia/Dubai",
    "AO": "Africa/Luanda",
    "BF": "Africa/Ouagadougou",
    "BI": "Africa/Bujumbura",
    "BJ": "Africa/Porto-Novo",
    "BW": "Africa/Gaborone",
    "CD": "Africa/Kinshasa",
    "CF": "Africa/Bangui",
    "CG": "Africa/Brazzaville",
    "CI": "Africa/Abidjan",
    "CM": "Africa/Douala",
    "CV": "Atlantic/Cape_Verde",
    "DJ": "Africa/Djibouti",
    "DZ": "Africa/Algiers",
    "EG": "Africa/Cairo",
    "ER": "Africa/Asmara",
    "ET": "Africa/Addis_Ababa",
    "GA": "Africa/Libreville",
    "GH": "Africa/Accra",
    "GN": "Africa/Conakry",
    "GQ": "Africa/Malabo",
    "GW": "Africa/Bissau",
    "KE": "Africa/Nairobi",
    "LR": "Africa/Monrovia",
    "LS": "Africa/Maseru",
    "LY": "Africa/Tripoli",
    "MA": "Africa/Casablanca",
    "MG": "Indian/Antananarivo",
    "ML": "Africa/Bamako",
    "MR": "Africa/Nouakchott",
    "MW": "Africa/Blantyre",
    "MZ": "Africa/Maputo",
    "NA": "Africa/Windhoek",
    "NE": "Africa/Niamey",
    "NG": "Africa/Lagos",
    "RW": "Africa/Kigali",
    "SC": "Indian/Mahe",
    "SD": "Africa/Khartoum",
    "SH": "Atlantic/St_Helena",
    "SL": "Africa/Freetown",
    "SN": "Africa/Dakar",
    "SO": "Africa/Mogadishu",
    "SS": "Africa/Juba",
    "ST": "Africa/Sao_Tome",
    "SZ": "Africa/Mbabane",
    "TD": "Africa/Ndjamena",
    "TG": "Africa/Lome",
    "TN": "Africa/Tunis",
    "TZ": "Africa/Dar_es_Salaam",
    "UG": "Africa/Kampala",
    "ZA": "Africa/Johannesburg",
    "ZM": "Africa/Lusaka",
    "ZW": "Africa/Harare",
    
    # Pacific & Oceania
    "AS": "Pacific/Pago_Pago",
    "AU": "Australia/Sydney",
    "CK": "Pacific/Rarotonga",
    "FJ": "Pacific/Fiji",
    "KI": "Pacific/Tarawa",
    "MV": "Indian/Maldives",
    "NC": "Pacific/Noumea",
    "NZ": "Pacific/Auckland",
    "PF": "Pacific/Tahiti",
    "PG": "Pacific/Port_Moresby",
    "SB": "Pacific/Guadalcanal",
    "TO": "Pacific/Tongatapu",
    "UM": "Pacific/Wake",
    "VU": "Pacific/Efate",
    "WS": "Pacific/Apia",
    
    # Special Territories
    "TF": "Indian/Kerguelen",
    
    # Antarctica & Special
    "AQ": "Antarctica/McMurdo",
    "ZZ": "UTC"
}


def get_fallback_timezone(country_code: str) -> str:
    """
    Get fallback timezone for countries not covered by OpenFlights.
    
    Args:
        country_code: ISO 2-letter country code
        
    Returns:
        IANA timezone identifier or 'UTC' if country not mapped
    """
    return COUNTRY_TIMEZONES.get(country_code, "UTC")
